### ISSUE TITLE
provide API for search

### ISSUE THREAD

**Issue by aliariff** [aliariff/rabatt#2]
We need an endpoint to handle the seaching/filter via the search bar.

<img width="1200" alt="screen shot 2017-06-29 at 20 03 27" src="https://user-images.githubusercontent.com/6806035/27702991-4365a8e4-5d06-11e7-945f-009394b53cc5.png">

**Comment by minemeraj** [comment]
The API is implemented. To search by title, make a rest call to: localhost:8080/rabatt/api/v1/discounts/search/findByTitle/{title}
Here, the title is the searched key. For example:
localhost:8080/rabatt/api/v1/discounts/search/findByTitle/half
