### ISSUE TITLE
delete register and manage discount btn

### ISSUE THREAD

**Issue by aliariff** [aliariff/rabatt#4]
<img width="681" alt="screen shot 2017-06-29 at 20 08 32" src="https://user-images.githubusercontent.com/6806035/27703143-c4b16ed8-5d06-11e7-9316-e0ea7230b7ba.png">
<img width="606" alt="screen shot 2017-06-29 at 20 08 39" src="https://user-images.githubusercontent.com/6806035/27703144-c4b995b8-5d06-11e7-8bfa-381b97230597.png">

**Comment by aymengan** [comment]
Which link should be link the "Manage Discount" to ?

**Comment by aliariff** [comment]
Just remove it
