### ISSUE TITLE
Enable Jenkins auto push

### ISSUE THREAD

**Issue by minemeraj** [aliariff/rabatt#8]
To enable jenkins auto push, we need to add a web hook to the github reppo
I don't have that access to add that hook
Only @aliariff  have the rights. Please add the web hook url to the github settings?
go to : Settings -> Integrations & Services -> Add Service -> Jenkins (GitHub plugin) You will see a text box labeled as Jenkins hook url. put this url there: http://jenkins.shahriar.io/github-webhook/
Than save.

**Comment by aliariff** [comment]
@minemeraj done
