### ISSUE TITLE
Make 2 Counter for vote

### ISSUE THREAD

**Issue by aliariff** [aliariff/rabatt#9]
handle like and dislike

**Comment by minemeraj** [comment]
"posVote" : 0
"negVote" : 0
Those two variables are provided for storing the like and dislike. posVote is for like and negVote for dislike.
visit: http://kildin.informatik.rwth-aachen.de/rabatt/api/v1/discounts

**Comment by minemeraj** [comment]
"posVote" : 0
"negVote" : 0
Those two variables are provided for storing the like and dislike. posVote is for like and negVote for dislike.
visit: http://kildin.informatik.rwth-aachen.de/rabatt/api/v1/discounts

**Comment by minemeraj** [comment]
"posVote" : 0
"negVote" : 0
Those two variables are provided for storing the like and dislike. posVote is for like and negVote for dislike.
visit: http://kildin.informatik.rwth-aachen.de/rabatt/api/v1/discounts
